### ISSUE TITLE
Adjust close button

### ISSUE THREAD

**Issue by hsukvn** [wediin/gallery#8]
點開圖後右上角的叉叉不是很明顯，可能可以調整一下顏色然後或參考 facebook web 版的叉叉

**Comment by nizi1127** [comment]
@

**Comment by nizi1127** [comment]
Update preview buttons style
[Updated in this commit](https://github.com/wediin/gallery/commit/080d9a6d124bdfd9cfe43c241ce20cd01097b46f)
